import type { Metadata } from "next";
import "./globals.css";
import "./fonts.css";
import { ClerkProvider } from "@clerk/nextjs";
import ConvexClientProvider from "../components/ConvexClientProvider";
import FaviconSwitcher from "../components/FaviconSwitcher";
import { Toaster } from "../components/ui/sonner";
import { shadcn } from "@clerk/themes";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
    icons: {
        icon: "/light_vision_map.ico",
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className="antialiased"
            >
                <FaviconSwitcher />
                <ClerkProvider dynamic appearance={{
                    theme: shadcn
                }}>
                    <ConvexClientProvider>{children}</ConvexClientProvider>
                </ClerkProvider>
                <Toaster />
            </body>
        </html>
    );
}
